baseURL = 'https://halter484.github.io/my-blog/'
languageCode = 'ja-jp'
title = 'KnittingDiary'
theme = 'PaperMod'
[params]
  description = '編み物の楽しさを記録するブログ。初心者向けの編み方や作品づくりのヒントを紹介します。'
  ShowDate = true
[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 10
[[menu.main]]
  name = 'カテゴリー'
  url = '/categories/'
  weight = 20
[[menu.main]]
  name = 'タグ'
  url = '/tags/'
  weight = 30  
[params.homeInfoParams]
  Title = 'KnittingDiary'
  Content = '編み物の楽しさや日々の制作記録、初心者向けの編み方や作品づくりのヒントを紹介しています。'
　footer = '© 2026 KnittingDiary'
